project:
  name: "Project Name Exemple"
  url: "https://exemple.com"
  email: "info@exemple.com"

db:
  dsn: "postgresql+psycopg2://test_user:pA$$W0rd@localhost/test_db"

smtp:
  host: "localhost"
  port: 1025
  username: ""
  password: ""
  use_tls: false

jwt:
  algorithm: "HS256"
  secret: ""
  ttl: 86400
