[project]
name = "pyapi-template"
version = "0.1.0"
description = "A production-ready Python API template built with modern tools and best practices."
authors = [
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 119

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
force-single-line = true
