name: Development CI pipeline
on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    env:
      ENV: 'dev'

    strategy:
      matrix:
        python-version: [ '3.12', '3.13' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          make setup_python

      - name: Analyze code
        run: |
          make lint
          make typecheck

  tests:
    runs-on: ubuntu-latest
    env:
      ENV: 'dev'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ytjyjdsq
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        # wait postgres to start
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres_container
        ports:
          - 5432:5432
      mailcather:
        image: schickling/mailcatcher
        ports:
          - 1025:1025

    strategy:
      matrix:
        python-version: [ '3.12', '3.13' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          make setup_python

      - name: Run Migrations & Tests
        run: |
          cp config-dist.yml config.yml
          make migrate
          make functional_test